apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-app
  name: argocd
  namespace: argocd
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: argocd-app
  source:
    repoURL: https://github.com/RPranav03/argocd.git
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
        - name: argocd-nginx
          image: nginx:latest
          ports:
            - containerPort: 80


